_group = {
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOVSS,MOVSS,MOVSS,MOVSS,",
    offsets = "0,4,8,12,",
    addresses = "0x1b20,0x1b39,0x1b54,0x1b6f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 4,
    pattern = "SSSS",
    opcodes = "MOVSS,MOVSS,MOVSS,MOVSS,",
    offsets = "0,4,8,12,",
    addresses = "0x1b34,0x1b4e,0x1b69,0x1b84,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 4,
  },
}
