_group = {
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOVSS,MOVSS,MOVSS,MOVSS,",
    offsets = "0,4,8,12,",
    addresses = "0x1800,0x1819,0x1834,0x184f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 4,
    pattern = "SSSS",
    opcodes = "MOVSS,MOVSS,MOVSS,MOVSS,",
    offsets = "0,4,8,12,",
    addresses = "0x1814,0x182e,0x1849,0x1864,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 4,
  },
}
